//! RuffleVita: translates a method's optimized op stream into a Rust
//! function for `generated.rs` (desktop development tool).
//!
//! `RUFFLEVITA_AOT_EMIT=<path to generated.rs>` turns it on and
//! `RUFFLEVITA_AOT_METHODS` lists the methods (`|`-separated, as `rv_prof`
//! names them; `prefix*` matches every method starting with `prefix`).
//! Each listed method is translated right after Ruffle verifies and
//! optimizes it, and the file is rewritten with every method
//! translated so far. Methods with try/catch, or with an op the translator
//! doesn't handle, are skipped and stay interpreted.
//!
//! The generated function keeps the operand stack in variables (the stack
//! depth at every op is known statically) and runs basic blocks from a
//! `loop { match block { .. } }`. A dataflow pass types every stack slot and
//! local as `Num` (always a number) or `Any`: numbers live unboxed as
//! `(f64, is_int)` (`n{k}`/`i{k}`, `ln{k}`/`li{k}`), everything else as
//! `Value` (`s{k}`, `l{k}`), and are boxed only where a `Value` is needed.

use crate::avm2::aot::{canonical, fingerprint, known_native, method_name, param_kinds, ParamKind};
use crate::avm2::method::Method;
use crate::avm2::op::Op;
use std::fmt::Write as _;
use std::sync::{Mutex, OnceLock};

struct Config {
    path: String,
    methods: Vec<String>,
}

fn config() -> Option<&'static Config> {
    static CONFIG: OnceLock<Option<Config>> = OnceLock::new();
    CONFIG
        .get_or_init(|| {
            let path = std::env::var("RUFFLEVITA_AOT_EMIT").ok()?;
            let methods = std::env::var("RUFFLEVITA_AOT_METHODS")
                .unwrap_or_default()
                .split('|')
                .map(|s| s.trim().to_owned())
                .filter(|s| !s.is_empty())
                .collect();
            Some(Config { path, methods })
        })
        .as_ref()
}

struct Translated {
    abc_method: u32,
    num_ops: usize,
    fingerprint: u64,
    name: String,
    code: String,
    leaf: bool,
}

static TRANSLATED: Mutex<Vec<Translated>> = Mutex::new(Vec::new());

/// Called after a method is verified and optimized.
pub fn after_verify(method: Method<'_>, ops: &[Op<'_>], has_exceptions: bool) {
    let Some(config) = config() else { return };
    let name = method_name(method);
    let listed = |m: &String| match m.strip_suffix('*') {
        Some(prefix) => name.starts_with(prefix),
        None => *m == name,
    };
    if !config.methods.iter().any(listed) {
        return;
    }
    let num_locals = method.body().map_or(0, |b| b.num_locals);
    let params = param_kinds(method);
    let fp = fingerprint(&canonical(&name, num_locals, &params, ops));
    let mut translated = TRANSLATED.lock().unwrap_or_else(|e| e.into_inner());
    if translated.iter().any(|t| t.fingerprint == fp) {
        return;
    }
    let fn_name = format!("m_{fp:016x}");
    match translate(&fn_name, &name, num_locals as usize, &params, ops, has_exceptions) {
        Ok((code, leaf)) => {
            tracing::info!("AOT translator: compiled {name} ({} ops{})", ops.len(), if leaf { ", leaf" } else { "" });
            translated.push(Translated {
                abc_method: method.abc_method_index(),
                num_ops: ops.len(),
                fingerprint: fp,
                name,
                code,
                leaf,
            });
            write_file(&config.path, &translated);
        }
        Err(why) => tracing::warn!("AOT translator: skipped {name}: {why}"),
    }
}

fn write_file(path: &str, methods: &[Translated]) {
    let mut out = String::from(
        "// Generated by RuffleVita's AOT translator (src/avm2/aot/translate.rs).\n\
         // Do not edit; regenerate with RUFFLEVITA_AOT_EMIT (see docs/AOT.md).\n\n\
         #![allow(unused_mut, unused_variables, unused_assignments, unreachable_code, unused_imports)]\n\
         #![allow(clippy::all)]\n\n\
         use super::rt;\n\
         use super::Entry;\n\
         use crate::avm2::activation::Activation;\n\
         use crate::avm2::op::Op;\n\
         use crate::avm2::value::Value;\n\
         use crate::avm2::Error;\n\n",
    );
    let mut sorted: Vec<&Translated> = methods.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));
    out += "pub(super) static TABLE: &[Entry] = &[\n";
    for t in &sorted {
        let _ = writeln!(
            out,
            "    Entry {{ abc_method: {}, num_ops: {}, fingerprint: 0x{:016x}, name: {:?}, run: m_{:016x}, leaf: {} }},",
            t.abc_method,
            t.num_ops,
            t.fingerprint,
            t.name,
            t.fingerprint,
            if t.leaf { format!("Some(l_{:016x})", t.fingerprint) } else { "None".to_owned() }
        );
    }
    out += "];\n";
    for t in &sorted {
        out += "\n";
        out += &t.code;
    }
    if let Err(e) = std::fs::write(path, out) {
        tracing::error!("AOT translator: couldn't write {path}: {e}");
    }
}


/// How an op uses the operand stack and where control goes after it.
#[derive(Clone, Copy, PartialEq)]
enum Flow {
    Next,
    /// Unconditional jump (or a switch); no fallthrough.
    Jump,
    /// Conditional branch: target or fallthrough.
    Branch,
    /// Return or throw.
    End,
}

/// (pops, pushes, flow, branch targets), or why the op isn't supported.
fn effect(op: &Op<'_>) -> Result<(usize, usize, Flow, Vec<usize>), String> {
    use Flow::*;
    let lazy = |m: &crate::avm2::multiname::Multiname<'_>| {
        m.has_lazy_name() as usize + m.has_lazy_ns() as usize
    };
    Ok(match op {
        Op::Nop | Op::Kill { .. } | Op::IncLocal { .. } | Op::IncLocalI { .. } | Op::DecLocal { .. } | Op::DecLocalI { .. } | Op::CoerceA => (0, 0, Next, vec![]),
        Op::PushDouble { .. } | Op::PushShort { .. } | Op::PushInt { .. } | Op::PushUint { .. } | Op::PushTrue | Op::PushFalse
        | Op::PushNull | Op::PushUndefined | Op::PushString { .. } | Op::PushNamespace { .. } | Op::GetLocal { .. }
        | Op::GetLocalSlot { .. } | Op::GetScriptGlobals { .. } | Op::GetOuterScope { .. } | Op::GetScopeObject { .. } => (0, 1, Next, vec![]),
        Op::GetLocal2 { .. } => (0, 2, Next, vec![]),
        Op::SetLocal { .. } | Op::Pop | Op::PushScope | Op::PushWith => (1, 0, Next, vec![]),
        Op::PopScope => (0, 0, Next, vec![]),
        Op::StoreLocal { .. } | Op::SetLocalGetLocal { .. } => (1, 1, Next, vec![]),
        Op::Dup => (1, 2, Next, vec![]),
        Op::Swap => (2, 2, Next, vec![]),
        Op::GetSlot { .. } | Op::Negate | Op::NegateI | Op::Increment | Op::IncrementI | Op::Decrement | Op::DecrementI
        | Op::BitNot | Op::Not | Op::CoerceB | Op::CoerceD | Op::CoerceI | Op::CoerceU | Op::CoerceO | Op::CoerceS
        | Op::ConvertO | Op::ConvertS | Op::Coerce { .. } | Op::TypeOf | Op::IsType { .. } | Op::AsType { .. } => (1, 1, Next, vec![]),
        Op::SetSlot { .. } | Op::SetSlotNoCoerce { .. } => (2, 0, Next, vec![]),
        Op::Add | Op::AddI | Op::Subtract | Op::SubtractI | Op::Multiply | Op::MultiplyI | Op::Divide | Op::Modulo
        | Op::BitAnd | Op::BitOr | Op::BitXor | Op::LShift | Op::RShift | Op::URShift | Op::Equals | Op::StrictEquals
        | Op::LessThan | Op::LessEquals | Op::GreaterThan | Op::GreaterEquals | Op::CoerceDSwapPop | Op::CoerceISwapPop
        | Op::CoerceUSwapPop | Op::CoerceSwapPop { .. } | Op::AsTypeLate | Op::IsTypeLate | Op::InstanceOf | Op::In => (2, 1, Next, vec![]),
        Op::GetPropertyStatic { multiname } | Op::GetPropertyFast { multiname } | Op::GetPropertySlow { multiname }
        | Op::GetSuper { multiname } | Op::GetDescendants { multiname } => (1 + lazy(multiname), 1, Next, vec![]),
        Op::SetPropertyStatic { multiname } | Op::SetPropertyFast { multiname } | Op::SetPropertySlow { multiname }
        | Op::InitProperty { multiname } | Op::SetSuper { multiname } => (2 + lazy(multiname), 0, Next, vec![]),
        Op::DeleteProperty { multiname } => (1 + lazy(multiname), 1, Next, vec![]),
        Op::FindProperty { multiname } | Op::FindPropStrict { multiname } => (lazy(multiname), 1, Next, vec![]),
        Op::CallMethod { num_args, push_return_value, .. } | Op::CallNative { num_args, push_return_value, .. } => {
            (1 + *num_args as usize, *push_return_value as usize, Next, vec![])
        }
        Op::CallStatic { num_args, .. } | Op::Construct { num_args } | Op::ConstructSlot { num_args, .. } => (1 + *num_args as usize, 1, Next, vec![]),
        Op::Call { num_args } => (2 + *num_args as usize, 1, Next, vec![]),
        Op::CallProperty { multiname, num_args } | Op::CallPropLex { multiname, num_args } | Op::CallSuper { multiname, num_args }
        | Op::ConstructProp { multiname, num_args } => (1 + lazy(multiname) + *num_args as usize, 1, Next, vec![]),
        Op::CallPropVoid { multiname, num_args } => (1 + lazy(multiname) + *num_args as usize, 0, Next, vec![]),
        Op::ConstructSuper { num_args } => (1 + *num_args as usize, 0, Next, vec![]),
        Op::NewArray { num_args } => (*num_args as usize, 1, Next, vec![]),
        Op::NewObject { num_args } => (2 * *num_args as usize, 1, Next, vec![]),
        Op::NewFunction { .. } => (0, 1, Next, vec![]),
        Op::ApplyType { num_types } => (1 + *num_types as usize, 1, Next, vec![]),
        Op::SetGlobalSlot { .. } => (1, 0, Next, vec![]),
        Op::Jump { offset } => (0, 0, Jump, vec![*offset]),
        Op::PopJump { offset } => (1, 0, Jump, vec![*offset]),
        Op::IfTrue { offset } | Op::IfFalse { offset } => (1, 0, Branch, vec![*offset]),
        Op::IfLt { offset } | Op::IfNotLt { offset } | Op::IfLe { offset } | Op::IfNotLe { offset } | Op::IfGt { offset }
        | Op::IfNotGt { offset } | Op::IfGe { offset } | Op::IfNotGe { offset } | Op::IfEq { offset } | Op::IfNotEq { offset }
        | Op::IfStrictEq { offset } | Op::IfNotStrictEq { offset } => (2, 0, Branch, vec![*offset]),
        Op::LookupSwitch(ls) => {
            let mut targets: Vec<usize> = ls.case_offsets.iter().map(|c| c.get()).collect();
            targets.push(ls.default_offset.get());
            (1, 0, Jump, targets)
        }
        Op::ReturnValue { .. } | Op::Throw => (1, 0, End, vec![]),
        Op::ReturnVoid { .. } => (0, 0, End, vec![]),
        other => {
            let text = format!("{other:?}");
            return Err(format!("unsupported op {}", &text[..text.find([' ', '{', '(']).unwrap_or(text.len())]));
        }
    })
}

/// Ops run through the interpreter's handler (`rt::delegate`).
fn delegated(op: &Op<'_>) -> bool {
    matches!(
        op,
        Op::PushString { .. } | Op::PushNamespace { .. } | Op::Call { .. } | Op::CallMethod { .. } | Op::CallProperty { .. }
            | Op::CallPropLex { .. } | Op::CallPropVoid { .. } | Op::CallStatic { .. } | Op::CallSuper { .. }
            | Op::GetPropertyStatic { .. } | Op::GetPropertyFast { .. } | Op::GetPropertySlow { .. } | Op::SetPropertyStatic { .. }
            | Op::SetPropertyFast { .. } | Op::SetPropertySlow { .. } | Op::InitProperty { .. } | Op::DeleteProperty { .. }
            | Op::GetSuper { .. } | Op::SetSuper { .. } | Op::In | Op::PushScope | Op::PushWith | Op::PopScope
            | Op::FindProperty { .. } | Op::FindPropStrict { .. } | Op::GetDescendants { .. } | Op::SetGlobalSlot { .. }
            | Op::Construct { .. } | Op::ConstructProp { .. } | Op::ConstructSlot { .. } | Op::ConstructSuper { .. }
            | Op::NewObject { .. } | Op::NewFunction { .. } | Op::ApplyType { .. } | Op::NewArray { .. } | Op::CoerceO | Op::CoerceS
            | Op::ConvertO | Op::ConvertS | Op::IsType { .. } | Op::IsTypeLate | Op::AsType { .. } | Op::AsTypeLate
            | Op::InstanceOf | Op::TypeOf | Op::Coerce { .. } | Op::CoerceSwapPop { .. } | Op::GetScopeObject { .. }
    )
}


/// What a stack slot or local holds at some point in the method.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Ty {
    /// Always a number: kept unboxed as `(f64, is_int)`.
    Num,
    /// Anything: kept as a `Value`.
    Any,
}

fn join(a: Ty, b: Ty) -> Ty {
    if a == Ty::Num && b == Ty::Num {
        Ty::Num
    } else {
        Ty::Any
    }
}

#[derive(Clone, PartialEq, Debug)]
struct State {
    stack: Vec<Ty>,
    locals: Vec<Ty>,
}

/// Inlined `Math` builtins: (Rust expression template over `{0}`/`{1}`, args).
fn math_call(op: &Op<'_>) -> Option<(&'static str, usize)> {
    let Op::CallNative { method, num_args, .. } = op else { return None };
    let (template, args) = match known_native(*method)? {
        "Math.sin" => ("f64::sin({0})", 1),
        "Math.cos" => ("f64::cos({0})", 1),
        "Math.tan" => ("f64::tan({0})", 1),
        "Math.sqrt" => ("f64::sqrt({0})", 1),
        "Math.abs" => ("f64::abs({0})", 1),
        "Math.atan" => ("f64::atan({0})", 1),
        "Math.asin" => ("f64::asin({0})", 1),
        "Math.acos" => ("f64::acos({0})", 1),
        "Math.exp" => ("f64::exp({0})", 1),
        "Math.log" => ("f64::ln({0})", 1),
        "Math.floor" => ("f64::floor({0})", 1),
        "Math.ceil" => ("f64::ceil({0})", 1),
        "Math.atan2" => ("f64::atan2({0}, {1})", 2),
        _ => return None,
    };
    (*num_args as usize == args).then_some((template, args))
}

/// Ops whose result is always a number.
fn numeric_result(op: &Op<'_>) -> bool {
    matches!(
        op,
        Op::PushDouble { .. } | Op::PushShort { .. } | Op::PushInt { .. } | Op::PushUint { .. } | Op::Subtract
            | Op::Multiply | Op::Divide | Op::Modulo | Op::Negate | Op::NegateI | Op::Increment | Op::IncrementI
            | Op::Decrement | Op::DecrementI | Op::BitNot | Op::BitAnd | Op::BitOr | Op::BitXor | Op::LShift
            | Op::RShift | Op::URShift | Op::AddI | Op::SubtractI | Op::MultiplyI | Op::CoerceD | Op::CoerceI
            | Op::CoerceU | Op::CoerceDSwapPop | Op::CoerceISwapPop | Op::CoerceUSwapPop
    ) || math_call(op).is_some()
}

/// Locals an op reads.
fn reads(op: &Op<'_>) -> Vec<usize> {
    match *op {
        Op::GetLocal { index } | Op::GetLocalSlot { index, .. } | Op::IncLocal { index } | Op::IncLocalI { index }
        | Op::DecLocal { index } | Op::DecLocalI { index } => vec![index as usize],
        Op::GetLocal2 { first, second } => vec![first as usize, second as usize],
        Op::SetLocalGetLocal { get, .. } => vec![get as usize],
        _ => vec![],
    }
}

/// The state after op `op` (the dataflow transfer function).
fn transfer(op: &Op<'_>, input: &State, effect: &Effect, num_local: &[bool]) -> State {
    let (pops, pushes, _, _) = effect;
    let mut out = input.clone();
    let args = out.stack.split_off(out.stack.len() - pops);
    let local = |k: u32| if num_local[k as usize] { input.locals[k as usize] } else { Ty::Any };
    let store = |out: &mut State, k: u32, ty: Ty| {
        out.locals[k as usize] = if num_local[k as usize] { ty } else { Ty::Any };
    };
    match *op {
        Op::GetLocal { index } => out.stack.push(local(index)),
        Op::GetLocal2 { first, second } => {
            out.stack.push(local(first));
            out.stack.push(local(second));
        }
        Op::SetLocal { index } => store(&mut out, index, args[0]),
        Op::StoreLocal { index } => {
            store(&mut out, index, args[0]);
            out.stack.push(args[0]);
        }
        Op::SetLocalGetLocal { set, get } => {
            store(&mut out, set, args[0]);
            out.stack.push(local(get));
        }
        Op::Kill { index } => store(&mut out, index, Ty::Any),
        Op::IncLocal { index } | Op::IncLocalI { index } | Op::DecLocal { index } | Op::DecLocalI { index } => {
            store(&mut out, index, Ty::Num)
        }
        Op::Dup => {
            out.stack.push(args[0]);
            out.stack.push(args[0]);
        }
        Op::Swap => {
            out.stack.push(args[1]);
            out.stack.push(args[0]);
        }
        Op::Add => out.stack.push(if args == [Ty::Num, Ty::Num] { Ty::Num } else { Ty::Any }),
        ref other if numeric_result(other) => {
            if *pushes > 0 {
                out.stack.push(Ty::Num);
            }
        }
        _ => {
            for _ in 0..*pushes {
                out.stack.push(Ty::Any);
            }
        }
    }
    out
}

type Effect = (usize, usize, Flow, Vec<usize>);

fn successors(i: usize, effect: &Effect) -> Vec<usize> {
    let mut next = effect.3.clone();
    if matches!(effect.2, Flow::Next | Flow::Branch) {
        next.push(i + 1);
    }
    next
}

/// The state at every reachable op.
fn analyze(ops: &[Op<'_>], effects: &[Effect], entry: &State, num_local: &[bool]) -> Result<Vec<Option<State>>, String> {
    let mut states: Vec<Option<State>> = vec![None; ops.len()];
    states[0] = Some(entry.clone());
    let mut work = vec![0usize];
    while let Some(i) = work.pop() {
        let input = states[i].clone().expect("queued ops have a state");
        if input.stack.len() < effects[i].0 {
            return Err(format!("stack underflow at op {i}"));
        }
        let out = transfer(&ops[i], &input, &effects[i], num_local);
        for t in successors(i, &effects[i]) {
            if t >= ops.len() {
                return Err(format!("control reaches past the end at op {i}"));
            }
            let merged = match &states[t] {
                None => out.clone(),
                Some(old) => {
                    if old.stack.len() != out.stack.len() {
                        return Err(format!("stack depth {} vs {} at op {t}", old.stack.len(), out.stack.len()));
                    }
                    State {
                        stack: old.stack.iter().zip(&out.stack).map(|(a, b)| join(*a, *b)).collect(),
                        locals: old.locals.iter().zip(&out.locals).map(|(a, b)| join(*a, *b)).collect(),
                    }
                }
            };
            if states[t].as_ref() != Some(&merged) {
                states[t] = Some(merged);
                work.push(t);
            }
        }
    }
    Ok(states)
}

fn translate(
    fn_name: &str,
    name: &str,
    num_locals: usize,
    params: &[ParamKind],
    ops: &[Op<'_>],
    has_exceptions: bool,
) -> Result<(String, bool), String> {
    if has_exceptions {
        return Err("has try/catch".into());
    }
    if params.len() + 1 > num_locals {
        return Err("more parameters than locals".into());
    }
    let effects: Vec<Effect> = ops.iter().map(effect).collect::<Result<_, _>>()?;

    // A leaf needs nothing from its own activation (see `aot::LeafFn`).
    let leaf = !params.contains(&ParamKind::Rest)
        && ops.iter().all(|op| match op {
            Op::CallNative { .. } => math_call(op).is_some(),
            Op::CallMethod { .. } | Op::Coerce { .. } | Op::ConstructSlot { .. } => true,
            Op::LookupSwitch(_) | Op::Throw
            | Op::GetPropertyFast { .. } | Op::SetPropertyFast { .. } => false,
            other => !delegated(other),
        });

    // Locals start as `this`, the (coerced) parameters, then undefined.
    let mut entry = State { stack: vec![], locals: vec![Ty::Any; num_locals] };
    for (k, p) in params.iter().enumerate() {
        if *p == ParamKind::Numeric {
            entry.locals[k + 1] = Ty::Num;
        }
    }

    // A local is kept unboxed if it's a number wherever it's read. Demoting
    // one can demote others, so repeat until nothing changes.
    let mut num_local = vec![true; num_locals];
    num_local[0] = false;
    let states = loop {
        let states = analyze(ops, &effects, &entry, &num_local)?;
        let mut changed = false;
        for (i, op) in ops.iter().enumerate() {
            let Some(st) = &states[i] else { continue };
            for k in reads(op) {
                if num_local[k] && st.locals[k] != Ty::Num {
                    num_local[k] = false;
                    changed = true;
                }
            }
        }
        if !changed {
            break states;
        }
    };

    let max_depth = (0..ops.len())
        .filter_map(|i| states[i].as_ref().map(|s| s.stack.len() + effects[i].1.max(1)))
        .max()
        .unwrap_or(0);

    // Basic blocks start at op 0, at branch targets, and after branches.
    let mut leader = vec![false; ops.len()];
    leader[0] = true;
    for (i, (_, _, flow, targets)) in effects.iter().enumerate() {
        for &t in targets {
            leader[t] = true;
        }
        if *flow != Flow::Next && i + 1 < ops.len() {
            leader[i + 1] = true;
        }
    }

    let mut out = String::new();
    let _ = writeln!(out, "/// {name}");
    let signature = "<'a, 'gc>(act: &mut Activation<'a, 'gc>, ops: &[Op<'gc>]) -> Result<Value<'gc>, Error<'gc>>";
    // A local's value at entry: from the activation's registers, or for a
    // leaf from `args` (`this` and the parameters; the rest are undefined).
    let num_args = params.len() + 1;
    let register = |k: usize| match (leaf, k < num_args) {
        (false, _) => format!("act.local_register({k})"),
        (true, true) => format!("args[{k}]"),
        (true, false) => "Value::Undefined".to_owned(),
    };
    if leaf {
        let leaf_name = fn_name.replacen("m_", "l_", 1);
        let registers: Vec<String> = (0..num_args).map(|k| format!("act.local_register({k})")).collect();
        let _ = writeln!(
            out,
            "#[inline(never)]\nfn {fn_name}{signature} {{\n    let args = [{}];\n    {leaf_name}(act, ops, &args)\n}}\n",
            registers.join(", ")
        );
        let _ = writeln!(
            out,
            "#[inline(never)]\nfn {leaf_name}<'a, 'gc>(act: &mut Activation<'a, 'gc>, ops: &[Op<'gc>], args: &[Value<'gc>]) -> Result<Value<'gc>, Error<'gc>> {{"
        );
    } else {
        let _ = writeln!(out, "#[inline(never)]\nfn {fn_name}{signature} {{");
    }
    for k in 0..num_locals {
        if !num_local[k] {
            let _ = writeln!(out, "    let mut l{k}: Value<'gc> = {};", register(k));
        } else if entry.locals[k] == Ty::Num {
            let _ = writeln!(out, "    let (mut ln{k}, mut li{k}): (f64, bool) = rt::unbox({});", register(k));
        } else {
            let _ = writeln!(out, "    let (mut ln{k}, mut li{k}): (f64, bool) = (0.0, false);");
        }
    }
    for k in 0..max_depth {
        let _ = writeln!(out, "    let mut s{k}: Value<'gc> = Value::Undefined;");
        let _ = writeln!(out, "    let (mut n{k}, mut i{k}): (f64, bool) = (0.0, false);");
    }
    out += "    let mut b: usize = 0;\n    loop {\n        match b {\n";

    let ctx = Ctx { states: &states, num_local: &num_local };
    let mut i = 0;
    while i < ops.len() {
        let start = i;
        if states[start].is_none() {
            i += 1;
            continue;
        }
        let mut body = String::new();
        loop {
            let input = states[i].as_ref().expect("ops inside a reachable block are reachable");
            let output = transfer(&ops[i], input, &effects[i], &num_local);
            let (stmt, flow) = ctx.emit(i, &ops[i], input, &output, &effects[i])?;
            body += &stmt;
            i += 1;
            if flow != Flow::Next {
                break;
            }
            if i >= ops.len() || leader[i] {
                // Fall through into the next block.
                body += &format!("                {}\n", ctx.edge(i - 1, &output, i));
                break;
            }
        }
        let _ = write!(out, "            {start} => {{\n{body}");
        out += "            }\n";
    }
    out += "            _ => unreachable!(\"AOT: bad block\"),\n        }\n    }\n}\n";
    Ok((out, leaf))
}

struct Ctx<'s> {
    states: &'s [Option<State>],
    num_local: &'s [bool],
}

impl Ctx<'_> {
    /// Going from op `from` (with stack `output`) to op `to`: box the slots
    /// the target expects as `Value`s, check the script timeout on backward
    /// branches, and jump.
    fn edge(&self, from: usize, output: &State, to: usize) -> String {
        let mut s = String::new();
        if let Some(target) = &self.states[to] {
            for (k, (have, want)) in output.stack.iter().zip(&target.stack).enumerate() {
                if *have == Ty::Num && *want == Ty::Any {
                    let _ = write!(s, "s{k} = rt::boxn((n{k}, i{k})); ");
                }
            }
        }
        if to <= from {
            s += "act.aot_timeout_check()?; ";
        }
        let _ = write!(s, "b = {to};");
        s
    }

    /// The statements for op `i`.
    fn emit(&self, i: usize, op: &Op<'_>, input: &State, output: &State, effect: &Effect) -> Result<(String, Flow), String> {
        let (pops, pushes, flow, targets) = effect;
        let d = input.stack.len();
        let base = d - pops;
        let ty = |k: usize| input.stack[k];
        // Slot `k` as a typed operand (an unboxed number or a Value).
        let opnd = |k: usize| if ty(k) == Ty::Num { format!("(n{k}, i{k})") } else { format!("s{k}") };
        // Slot `k` as a Value.
        let val = |k: usize| if ty(k) == Ty::Num { format!("rt::boxn((n{k}, i{k}))") } else { format!("s{k}") };
        let set_num = |k: usize, e: String| format!("(n{k}, i{k}) = {e};");
        let set_val = |k: usize, e: String| format!("s{k} = {e};");
        let local_val = |k: u32| {
            if self.num_local[k as usize] { format!("rt::boxn((ln{k}, li{k}))") } else { format!("l{k}") }
        };
        let get_local = |slot: usize, k: u32| {
            if self.num_local[k as usize] { set_num(slot, format!("(ln{k}, li{k})")) } else { set_val(slot, format!("l{k}")) }
        };
        let set_local = |k: u32, slot: usize| {
            if self.num_local[k as usize] {
                // A non-number stored into an unboxed local is never read.
                if ty(slot) == Ty::Num { format!("(ln{k}, li{k}) = (n{slot}, i{slot});") } else { String::new() }
            } else {
                format!("l{k} = {};", val(slot))
            }
        };
        let branch = |cond: String, target: usize| {
            format!("if {cond} {{ {} }} else {{ {} }}", self.edge(i, output, target), self.edge(i, output, i + 1))
        };
        let line = |text: String| if text.is_empty() { text } else { format!("                {text}\n") };

        if let Some((template, n)) = math_call(op) {
            let receiver = d - 1 - n;
            let args: Vec<String> = (0..n).map(|k| format!("rt::t_as_f64({})", opnd(receiver + 1 + k))).collect();
            let mut expr = template.to_owned();
            for (k, a) in args.iter().enumerate() {
                expr = expr.replace(&format!("{{{k}}}"), a);
            }
            let Op::CallNative { push_return_value, .. } = op else { unreachable!() };
            let stmt = if *push_return_value { line(set_num(receiver, format!("({expr}, false)"))) } else { String::new() };
            return Ok((stmt, Flow::Next));
        }

        match op {
            Op::CallMethod { push_return_value, .. } => {
                let args: Vec<String> = (base + 1..d).map(val).collect();
                let call = format!("rt::call_method(act, &ops[{i}], {}, &[{}])?", val(base), args.join(", "));
                let stmt = if *push_return_value { set_val(base, call) } else { format!("{call};") };
                return Ok((line(stmt), Flow::Next));
            }
            Op::Coerce { .. } => {
                return Ok((line(set_val(base, format!("rt::coerce(act, &ops[{i}], {})?", val(base)))), Flow::Next));
            }
            Op::ConstructSlot { .. } => {
                let args: Vec<String> = (base + 1..d).map(val).collect();
                let call = format!("rt::construct_slot(act, &ops[{i}], {}, &[{}])?", val(base), args.join(", "));
                return Ok((line(set_val(base, call)), Flow::Next));
            }
            Op::GetPropertyFast { .. } if *pops == 2 => {
                let call = format!("rt::get_property_fast(act, &ops[{i}], {}, {})?", val(base), val(base + 1));
                return Ok((line(set_val(base, call)), Flow::Next));
            }
            Op::SetPropertyFast { .. } if *pops == 3 => {
                let call = format!("rt::set_property_fast(act, &ops[{i}], {}, {}, {})?;", val(base), val(base + 1), val(base + 2));
                return Ok((line(call), Flow::Next));
            }
            _ => {}
        }

        if delegated(op) || matches!(op, Op::CallNative { .. }) {
            let operands: Vec<String> = (base..d).map(val).collect();
            let call = format!("rt::delegate(act, &ops[{i}], &[{}], {})?", operands.join(", "), *pushes > 0);
            let stmt = if *pushes > 0 { set_val(base, call) } else { format!("{call};") };
            let text = format!("{op:?}");
            let kind = &text[..text.find([' ', '{', '(']).unwrap_or(text.len())];
            return Ok((line(format!("{stmt} // {kind}")), *flow));
        }

        let t1 = d.wrapping_sub(1);
        let t2 = d.wrapping_sub(2);
        let stmt = match *op {
            Op::Nop | Op::CoerceA | Op::Pop => String::new(),
            Op::PushDouble { value } => set_num(d, format!("(f64::from_bits(0x{:016x}), false)", value.to_bits())),
            Op::PushShort { value } => set_num(d, format!("({}f64, true)", value)),
            Op::PushInt { value } => set_num(d, format!("rt::from_i32({value}i32)")),
            Op::PushUint { value } => set_num(d, format!("rt::from_u32({value}u32)")),
            Op::PushTrue => set_val(d, "Value::Bool(true)".into()),
            Op::PushFalse => set_val(d, "Value::Bool(false)".into()),
            Op::PushNull => set_val(d, "Value::Null".into()),
            Op::PushUndefined => set_val(d, "Value::Undefined".into()),
            Op::GetLocal { index } => get_local(d, index),
            Op::GetLocal2 { first, second } => format!("{} {}", get_local(d, first), get_local(d + 1, second)),
            Op::SetLocal { index } | Op::StoreLocal { index } => set_local(index, t1),
            Op::SetLocalGetLocal { set, get } => format!("{} {}", set_local(set, t1), get_local(t1, get)),
            Op::Kill { index } => {
                if self.num_local[index as usize] { String::new() } else { format!("l{index} = Value::Undefined;") }
            }
            Op::IncLocal { index } | Op::IncLocalI { index } | Op::DecLocal { index } | Op::DecLocalI { index } => {
                let f = match op {
                    Op::IncLocal { .. } => "t_inc",
                    Op::IncLocalI { .. } => "t_inc_i",
                    Op::DecLocal { .. } => "t_dec",
                    _ => "t_dec_i",
                };
                if self.num_local[index as usize] {
                    format!("(ln{index}, li{index}) = rt::{f}(act, (ln{index}, li{index}))?;")
                } else {
                    format!("l{index} = rt::boxn(rt::{f}(act, l{index})?);")
                }
            }
            Op::Dup => {
                if ty(t1) == Ty::Num { set_num(d, format!("(n{t1}, i{t1})")) } else { set_val(d, format!("s{t1}")) }
            }
            Op::Swap => match (ty(t2), ty(t1)) {
                (Ty::Num, Ty::Num) => format!("std::mem::swap(&mut n{t2}, &mut n{t1}); std::mem::swap(&mut i{t2}, &mut i{t1});"),
                (Ty::Any, Ty::Any) => format!("std::mem::swap(&mut s{t2}, &mut s{t1});"),
                (Ty::Num, Ty::Any) => format!("let t = s{t1}; (n{t1}, i{t1}) = (n{t2}, i{t2}); s{t2} = t;"),
                (Ty::Any, Ty::Num) => format!("let t = s{t2}; (n{t2}, i{t2}) = (n{t1}, i{t1}); s{t1} = t;"),
            },
            Op::GetSlot { index } => set_val(t1, format!("rt::get_slot(act, {}, {index})?", val(t1))),
            Op::GetLocalSlot { index, slot } => set_val(d, format!("rt::get_slot(act, {}, {slot})?", local_val(index))),
            Op::SetSlot { index } => format!("rt::set_slot(act, {}, {}, {index})?;", val(t2), val(t1)),
            Op::SetSlotNoCoerce { index } => format!("rt::set_slot_no_coerce(act, {}, {}, {index})?;", val(t2), val(t1)),
            Op::GetScriptGlobals { .. } => set_val(d, format!("rt::script_globals(act, &ops[{i}])?")),
            Op::GetOuterScope { index } => set_val(d, format!("rt::outer_scope(act, {index})")),
            Op::Add => {
                if output.stack[t2] == Ty::Num {
                    set_num(t2, format!("rt::t_add({}, {})", opnd(t2), opnd(t1)))
                } else {
                    set_val(t2, format!("rt::add(act, &ops[{i}], {}, {})?", val(t2), val(t1)))
                }
            }
            Op::Subtract => set_num(t2, format!("rt::t_sub(act, &ops[{i}], {}, {})?", opnd(t2), opnd(t1))),
            Op::Multiply => set_num(t2, format!("rt::t_mul(act, &ops[{i}], {}, {})?", opnd(t2), opnd(t1))),
            Op::Divide | Op::Modulo | Op::BitAnd | Op::BitOr | Op::BitXor | Op::LShift | Op::RShift | Op::URShift
            | Op::AddI | Op::SubtractI | Op::MultiplyI => {
                let f = match op {
                    Op::Divide => "t_div",
                    Op::Modulo => "t_mod",
                    Op::BitAnd => "t_bit_and",
                    Op::BitOr => "t_bit_or",
                    Op::BitXor => "t_bit_xor",
                    Op::LShift => "t_lshift",
                    Op::RShift => "t_rshift",
                    Op::URShift => "t_urshift",
                    Op::AddI => "t_add_i",
                    Op::SubtractI => "t_sub_i",
                    _ => "t_mul_i",
                };
                set_num(t2, format!("rt::{f}(act, {}, {})?", opnd(t2), opnd(t1)))
            }
            Op::Negate | Op::NegateI | Op::Increment | Op::IncrementI | Op::Decrement | Op::DecrementI | Op::BitNot
            | Op::CoerceD | Op::CoerceI | Op::CoerceU => {
                let f = match op {
                    Op::Negate => "t_neg",
                    Op::NegateI => "t_neg_i",
                    Op::Increment => "t_inc",
                    Op::IncrementI => "t_inc_i",
                    Op::Decrement => "t_dec",
                    Op::DecrementI => "t_dec_i",
                    Op::BitNot => "t_bit_not",
                    Op::CoerceD => "t_coerce_d",
                    Op::CoerceI => "t_coerce_i",
                    _ => "t_coerce_u",
                };
                set_num(t1, format!("rt::{f}(act, {})?", opnd(t1)))
            }
            Op::CoerceDSwapPop | Op::CoerceISwapPop | Op::CoerceUSwapPop => {
                let f = match op {
                    Op::CoerceDSwapPop => "t_coerce_d",
                    Op::CoerceISwapPop => "t_coerce_i",
                    _ => "t_coerce_u",
                };
                set_num(t2, format!("rt::{f}(act, {})?", opnd(t1)))
            }
            Op::Not => set_val(t1, format!("Value::Bool(!rt::t_truthy({}))", opnd(t1))),
            Op::CoerceB => set_val(t1, format!("Value::Bool(rt::t_truthy({}))", opnd(t1))),
            Op::LessThan => set_val(t2, format!("Value::Bool(rt::t_lt(act, {}, {})?.unwrap_or(false))", opnd(t2), opnd(t1))),
            Op::GreaterThan => set_val(t2, format!("Value::Bool(rt::t_lt(act, {}, {})?.unwrap_or(false))", opnd(t1), opnd(t2))),
            Op::LessEquals => set_val(t2, format!("Value::Bool(!rt::t_lt(act, {}, {})?.unwrap_or(true))", opnd(t1), opnd(t2))),
            Op::GreaterEquals => set_val(t2, format!("Value::Bool(!rt::t_lt(act, {}, {})?.unwrap_or(true))", opnd(t2), opnd(t1))),
            Op::Equals => set_val(t2, format!("Value::Bool(rt::t_eq(act, {}, {})?)", opnd(t2), opnd(t1))),
            Op::StrictEquals => set_val(t2, format!("Value::Bool(rt::t_strict_eq({}, {}))", opnd(t2), opnd(t1))),
            Op::Jump { offset } | Op::PopJump { offset } => self.edge(i, output, offset),
            Op::IfTrue { offset } => branch(format!("rt::t_truthy({})", opnd(t1)), offset),
            Op::IfFalse { offset } => branch(format!("!rt::t_truthy({})", opnd(t1)), offset),
            Op::IfLt { offset } | Op::IfNotLt { offset } | Op::IfGe { offset } | Op::IfNotGe { offset } | Op::IfGt { offset }
            | Op::IfNotGt { offset } | Op::IfLe { offset } | Op::IfNotLe { offset } => {
                let (a, b) = (opnd(t2), opnd(t1));
                let (x, y, test) = match op {
                    Op::IfLt { .. } => (&a, &b, "== Some(true)"),
                    Op::IfNotLt { .. } => (&a, &b, "!= Some(true)"),
                    Op::IfGe { .. } => (&a, &b, "== Some(false)"),
                    Op::IfNotGe { .. } => (&a, &b, "!= Some(false)"),
                    Op::IfGt { .. } => (&b, &a, "== Some(true)"),
                    Op::IfNotGt { .. } => (&b, &a, "!= Some(true)"),
                    Op::IfLe { .. } => (&b, &a, "== Some(false)"),
                    _ => (&b, &a, "!= Some(false)"),
                };
                branch(format!("rt::t_lt(act, {x}, {y})? {test}"), offset)
            }
            Op::IfEq { offset } | Op::IfNotEq { offset } => {
                let not = if matches!(op, Op::IfNotEq { .. }) { "!" } else { "" };
                branch(format!("{not}rt::t_eq(act, {}, {})?", opnd(t2), opnd(t1)), offset)
            }
            Op::IfStrictEq { offset } | Op::IfNotStrictEq { offset } => {
                let not = if matches!(op, Op::IfNotStrictEq { .. }) { "!" } else { "" };
                branch(format!("{not}rt::t_strict_eq({}, {})", opnd(t2), opnd(t1)), offset)
            }
            Op::LookupSwitch(_) => {
                // Every target must take the stack as it is (no boxing).
                let plain: Vec<String> = targets.iter().map(|&t| self.edge(i, output, t)).collect();
                if plain.iter().any(|e| e.contains("boxn")) {
                    return Err("lookupswitch with unboxed numbers on the stack".into());
                }
                format!("act.aot_timeout_check()?; b = act.aot_lookup_switch({}, &ops[{i}]);", val(t1))
            }
            Op::ReturnValue { .. } => format!("return act.aot_return_value({}, &ops[{i}]);", val(t1)),
            Op::ReturnVoid { .. } => format!("return Ok(act.aot_return_void(&ops[{i}]));"),
            Op::Throw => format!("rt::delegate(act, &ops[{i}], &[{}], false)?; unreachable!(\"throw returned\");", val(t1)),
            ref other => return Err(format!("no translation for {other:?}")),
        };
        Ok((line(stmt), *flow))
    }
}
